---
profiles:
  "profile_name":
    url: "ldap://ldap.vip.example.com:389"
    use_tls: true
    bind_dn: "cn=bar,dc=example,dc=com"
    bind_pw: "secret"
  "another_profile":
    url: "ldap://active-directory.example.com"
    use_tls: true
    bind_dn: "cn=foo,dc=example,dc=com"
    bind_pw: "secret"
