---
  profiles:
    description: "A list of available ldap servers"
    type: "array"
    items:
      required: true
      type: "object"
      properties:
        name:
          description: "Profile name"
          type: "string"
          secret: false
          required: true
        url:
          description: "LDAP URL."
          type: "string"
          secret: false
          required: true
        use_tls:
          description: "Enable TLS when connecting to ldap server."
          type: "boolean"
          secret: false
          required: true
        bind_dn:
          description: "Bind using Distinguished Name."
          type: "string"
          secret: false
          required: true
        bind_pw:
          description: "Distinguished Name password."
          type: "string"
          secret: false
          required: true
  available_profiles:
    desciption: "The list of available profiles to be presented in the WebUI's dropdown list"
    type: "array"
    items:
      type: "string"
    secret: false
    required: true
